// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	ptySpawn: (command: string, args: string[], cwd: string | null, cols: number, rows: number) => typedError<string, string>(__TAURI_INVOKE("pty_spawn", { command, args, cwd, cols, rows })),
	ptyWrite: (id: string, data: string) => typedError<null, string>(__TAURI_INVOKE("pty_write", { id, data })),
	ptyResize: (id: string, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("pty_resize", { id, cols, rows })),
	ptyKill: (id: string) => typedError<null, string>(__TAURI_INVOKE("pty_kill", { id })),
	ptyList: () => __TAURI_INVOKE<string[]>("pty_list"),
	resolveClaudeBin: () => __TAURI_INVOKE<string | null>("resolve_claude_bin"),
	/**
	 *  Return the user's HOME directory as a string, or an empty string if HOME
	 *  is unset. Exposed as a Tauri command so the frontend can derive paths
	 *  instead of hard-coding a developer's home directory.
	 */
	getHomeDir: () => __TAURI_INVOKE<string>("get_home_dir"),
	listProjects: () => __TAURI_INVOKE<ProjectInfo[]>("list_projects"),
	listSessions: (folder: string, limit: number | null) => __TAURI_INVOKE<SessionInfo[]>("list_sessions", { folder, limit }),
	replaySession: (filePath: string) => typedError<ReplayResult, string>(__TAURI_INVOKE("replay_session", { filePath })),
	replaySessionPaged: (filePath: string, query: ReplayPageQuery) => typedError<ReplayPage, string>(__TAURI_INVOKE("replay_session_paged", { filePath, query })),
	searchSessions: (query: string, limit: number | null) => __TAURI_INVOKE<SearchHit[]>("search_sessions", { query, limit }),
	searchFiles: (cwd: string, query: string, limit: number | null) => typedError<FileHit[], string>(__TAURI_INVOKE("search_files", { cwd, query, limit })),
	readSessionTitles: () => __TAURI_INVOKE<{ [key in string]: string }>("read_session_titles"),
	renameSession: (filePath: string, newTitle: string) => typedError<null, string>(__TAURI_INVOKE("rename_session", { filePath, newTitle })),
	exportAllProjects: (outPath: string) => typedError<ExportResult, string>(__TAURI_INVOKE("export_all_projects", { outPath })),
	exportProject: (folder: string, outPath: string) => typedError<ExportResult, string>(__TAURI_INVOKE("export_project", { folder, outPath })),
	importBackup: (archivePath: string) => typedError<ImportResult, string>(__TAURI_INVOKE("import_backup", { archivePath })),
	archiveSession: (filePath: string) => typedError<string, string>(__TAURI_INVOKE("archive_session", { filePath })),
	deleteSession: (filePath: string) => typedError<null, string>(__TAURI_INVOKE("delete_session", { filePath })),
	readConfig: (kind: string) => typedError<ConfigFile, string>(__TAURI_INVOKE("read_config", { kind })),
	writeConfig: (kind: string, content: string) => typedError<WriteResult, string>(__TAURI_INVOKE("write_config", { kind, content })),
	listSkills: () => typedError<SkillInfo[], string>(__TAURI_INVOKE("list_skills")),
	listAgents: () => typedError<AgentInfo[], string>(__TAURI_INVOKE("list_agents")),
	listCommands: () => typedError<CommandInfo[], string>(__TAURI_INVOKE("list_commands")),
	listPlugins: () => typedError<PluginInfo[], string>(__TAURI_INVOKE("list_plugins")),
	setPluginEnabled: (id: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_plugin_enabled", { id, enabled })),
	savePasteImage: (bytes: number[], ext: string) => typedError<string, string>(__TAURI_INVOKE("save_paste_image", { bytes, ext })),
	listModels: () => typedError<ModelOption[], string>(__TAURI_INVOKE("list_models")),
	readImageDataUrl: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_image_data_url", { path })),
	readMarkdownFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_markdown_file", { path })),
	writeTextFile: (filePath: string, content: string) => typedError<null, string>(__TAURI_INVOKE("write_text_file", { filePath, content })),
	claudeSend: (args: ClaudeSendArgs) => typedError<null, string>(__TAURI_INVOKE("claude_send", { args })),
	claudeCancel: (requestId: string) => typedError<null, string>(__TAURI_INVOKE("claude_cancel", { requestId })),
};

/** Events */
export const events = {
	claudeDoneEvent: makeEvent<ClaudeDoneEvent>("claude-done-event"),
	claudeStderrEvent: makeEvent<ClaudeStderrEvent>("claude-stderr-event"),
	claudeStreamEvent: makeEvent<ClaudeStreamEvent>("claude-stream-event"),
	ptyDataEvent: makeEvent<PtyDataEvent>("pty-data-event"),
	ptyExitEvent: makeEvent<PtyExitEvent>("pty-exit-event"),
};

/* Types */
export type AgentInfo = {
	name: string,
	description: string,
	path: string,
	source: string,
	model: string | null,
	tools: string[],
};

export type ClaudeDoneEvent = {
	request_id: string,
	code: number | null,
	error: string | null,
};

export type ClaudeSendArgs = {
	request_id: string,
	prompt: string,
	cwd: string,
	resume_session_id: string | null,
	claude_bin: string | null,
	extra_dirs?: string[],
	skip_permissions?: boolean,
	permission_mode: string | null,
	model: string | null,
	/**  Replaces the default system prompt for this session. */
	system_prompt: string | null,
	/**  Appended after the default system prompt for this session. */
	append_system_prompt: string | null,
	/**  Reasoning effort level: "low" | "medium" | "high" | "xhigh" | "max". */
	effort: string | null,
};

export type ClaudeStderrEvent = {
	request_id: string,
	line: string,
};

export type ClaudeStreamEvent = {
	request_id: string,
	line: string,
};

export type CommandInfo = {
	name: string,
	description: string,
	path: string,
	source: string,
};

export type ConfigFile = {
	kind: string,
	path: string,
	exists: boolean,
	content: string,
	valid_json: boolean,
	parse_error: string | null,
};

export type ExportResult = {
	path: string,
	project_count: number,
	session_count: number,
	byte_size: number,
};

export type FileHit = {
	rel_path: string,
	abs_path: string,
};

export type ImportResult = {
	project_count: number,
	imported_session_count: number,
	skipped_session_count: number,
	titles_added: number,
	titles_kept: number,
	source_path: string,
};

export type ModelOption = {
	id: string,
	family: string,
	label: string,
	thinking: boolean,
	context_1m: boolean,
	source: string,
};

export type PluginInfo = {
	id: string,
	enabled: boolean,
	installed: boolean,
	version: string | null,
	install_path: string | null,
};

export type ProjectInfo = {
	name: string,
	path: string,
	folder: string,
	session_count: number,
	last_activity_ms: number,
};

export type PtyDataEvent = {
	id: string,
	data: string,
};

export type PtyExitEvent = {
	id: string,
	code: number | null,
};

export type ReplayEntry = {
	id: string,
	kind: string,
	role: string,
	text: string,
	timestamp: string | null,
	tool_name: string | null,
	tool_use_id: string | null,
	tool_input_json: string | null,
	tool_output_text: string | null,
	is_error: boolean,
	is_meta: boolean,
};

export type ReplayMessage = {
	id: string,
	role: string,
	text: string,
	timestamp: string | null,
	tool_name: string | null,
	is_meta: boolean,
};

export type ReplayPage = {
	session_id: string | null,
	messages: ReplayMessage[],
	entries: ReplayEntry[],
	cwd: string | null,
	total_input_tokens: number,
	total_output_tokens: number,
	total_cache_read_tokens: number,
	total_cache_creation_tokens: number,
	context_window: number,
	turn_count: number,
	last_input_tokens: number,
	last_output_tokens: number,
	last_cache_read_tokens: number,
	last_cache_creation_tokens: number,
	total_message_count: number,
	returned_message_count: number,
	has_more_before: boolean,
	earliest_uuid: string | null,
};

export type ReplayPageQuery = {
	limit: number | null,
	beforeUuid: string | null,
};

export type ReplayResult = {
	session_id: string | null,
	messages: ReplayMessage[],
	entries: ReplayEntry[],
	cwd: string | null,
	total_input_tokens: number,
	total_output_tokens: number,
	total_cache_read_tokens: number,
	total_cache_creation_tokens: number,
	context_window: number,
	turn_count: number,
	last_input_tokens: number,
	last_output_tokens: number,
	last_cache_read_tokens: number,
	last_cache_creation_tokens: number,
};

export type SearchHit = {
	session_id: string,
	file_path: string,
	project_folder: string,
	project_path: string,
	project_name: string,
	role: string,
	snippet: string,
	timestamp: string | null,
	mtime_ms: number,
	uuid: string | null,
	entry_kind: string | null,
	tool_name: string | null,
};

export type SessionInfo = {
	id: string,
	cwd: string | null,
	first_prompt: string | null,
	last_activity: string | null,
	mtime_ms: number,
	message_count: number,
	file_path: string,
};

export type SkillInfo = {
	name: string,
	description: string,
	source: string,
	path: string,
};

export type WriteResult = {
	path: string,
	backup: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

